services:
    mysql:
      image: mysql:latest
      environment:
        MYSQL_DATABASE: 'nlw'
        MYSQL_USER: 'node'
        MYSQL_PASSWORD: 'nlw_passwd'
        MYSQL_ROOT_PASSWORD: 'root'
      ports:
        - '3306:3306'
      volumes:
        - mysql-data:/home/fulvio/Dev/nlw/mysql
volumes:
  mysql-data: